In [1]:
import numpy as np
import pandas as pd
from scipy.io import loadmat
import random
import matplotlib.pyplot as plt

# Q3 example

In [9]:
from numpy import linalg as LA

In [10]:
M = np.matrix([[1,1],[1,1]],dtype=float)
M

matrix([[ 1.,  1.],
        [ 1.,  1.]])

In [11]:
LA.eigvals(M)

array([ 2.,  0.])

In [12]:
eta = float(1)/3
eta

0.3333333333333333

In [13]:
I = np.identity(2)
I

array([[ 1.,  0.],
       [ 0.,  1.]])

In [14]:
beta_hat = np.array([2,2]).T
beta_hat

array([2, 2])

In [15]:
Y = LA.matrix_power(I - eta*M,3)
LHS = LA.norm(np.dot(Y,beta_hat))
LHS

0.10475656017578497

In [16]:
N=3
c = np.exp(-2*N*eta*2)
c

0.018315638888734179

In [17]:
RHS = c*LA.norm(beta_hat)
RHS

0.051804449839951923

In [18]:
LHS<RHS

False